# Generated by Django 3.2.8 on 2021-10-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(default='Custom category', max_length=100),
            preserve_default=False,
        ),
    ]
